/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PIO0_29_FUNC_ALT1 0x01u /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO0_30_FUNC_ALT1 0x01u /*!<@brief Selects pin function.: Alternative connection 1. */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_26_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_1_FUNC_ALT5 0x05u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_1_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_2_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_3_SLEW_FAST 0x01u
/*!
 * @brief Analog switch input control. Usable only if DIGIMODE = 0b0: Analog switch is closed. */
#define PIO1_8_ASW_ENABLE 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_8_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_8_MODE_PULL_DOWN 0x01u
/*!
 * @brief Analog switch input control. Usable only if DIGIMODE = 0b0: Analog switch is closed. */
#define PIO1_9_ASW_ENABLE 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_9_MODE_PULL_UP 0x02u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitGT202Shield(void); /* Function assigned for the Cortex-M33 (Core #0) */

/*!
 * @brief Analog switch input control. Usable only if DIGIMODE = 0b0: Analog switch is closed. */
#define PIO0_15_ASW_ENABLE 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_15_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO0_26_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO0_26_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO1_1_FUNC_ALT5 0x05u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_1_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_2_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_2_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO1_3_FUNC_ALT6 0x06u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO1_3_SLEW_FAST 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_4_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_4_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Digital mode.: Digital mode, digital input is enabled. */
#define PIO1_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_7_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO1_7_MODE_PULL_DOWN 0x01u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSilex2401Shield(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
